name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: |
        # Run npm audit and capture output
        npm audit --audit-level=moderate --json > audit-results.json || true
        
        # Display audit results
        npm audit --audit-level=moderate || true
        
        # Check if there are any vulnerabilities above low level
        VULN_COUNT=$(cat audit-results.json | jq '.metadata.vulnerabilities.moderate + .metadata.vulnerabilities.high + .metadata.vulnerabilities.critical' 2>/dev/null || echo "0")
        
        if [ "$VULN_COUNT" -gt "0" ]; then
          echo "::warning::Found $VULN_COUNT moderate or higher severity vulnerabilities"
          echo "Please review and fix these vulnerabilities"
        else
          echo "No moderate or higher severity vulnerabilities found"
        fi

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"

    - name: Run ESLint Security Plugin
      run: |
        # Install security-focused ESLint plugin
        npm install --save-dev eslint-plugin-security --no-save
        
        # Create temporary eslint config for security scan
        cat > .eslintrc.security.json << 'EOF'
        {
          "extends": ["plugin:security/recommended"],
          "plugins": ["security"],
          "parserOptions": {
            "ecmaVersion": 2022,
            "sourceType": "module"
          },
          "env": {
            "node": true,
            "browser": true,
            "es6": true
          }
        }
        EOF
        
        # Run security-focused linting
        npx eslint --config .eslintrc.security.json src/ --ext .js,.jsx || true

    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential hardcoded secrets..."
        
        # Check for common secret patterns
        if grep -r -E "(password|secret|key|token)" --include="*.js" --include="*.jsx" --include="*.ts" --include="*.tsx" src/ | grep -E "(=|:)" | grep -v -E "(console\.|\.log|test|spec|mock)" | head -20; then
          echo "::warning::Potential hardcoded secrets found. Please review the above matches."
        else
          echo "No obvious hardcoded secrets detected"
        fi
        
        # Check for API keys and tokens
        if grep -r -E "(api_key|apikey|access_token|secret_key)" --include="*.js" --include="*.jsx" src/ | head -10; then
          echo "::warning::Potential API keys or tokens found. Please review."
        fi

    - name: Dependency License Check
      run: |
        # Install license checker
        npm install --save-dev license-checker --no-save
        
        # Check licenses
        npx license-checker --summary --excludePrivatePackages || true
        
        # Check for problematic licenses
        echo "Checking for restrictive licenses..."
        npx license-checker --failOn 'GPL-2.0; GPL-3.0; AGPL-1.0; AGPL-3.0' --excludePrivatePackages || echo "Some dependencies may have restrictive licenses"

    - name: Security Summary
      run: |
        echo "## Security Scan Summary"
        echo "- npm audit: Completed"
        echo "- CodeQL analysis: Completed"
        echo "- ESLint security scan: Completed"
        echo "- Secret detection: Completed"
        echo "- License check: Completed"
        echo ""
        echo "Review the logs above for any security findings that need attention."